# Generated by Django 4.2.3 on 2023-08-12 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tercera_preentrega_app', '0003_rename_usuario_perfil_user_remove_perfil_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accesorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tercera_preentrega_app.accesorio')),
                ('consola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tercera_preentrega_app.consola')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videojuego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tercera_preentrega_app.videojuego')),
            ],
        ),
    ]
